
[log]
    level = "trace"

[process]
    title = "wdac"

[app]
    name = "Audit System"
    clientUrl = "https://audit.wildduck.email/"

    [app.pgp]
        version = "WildDuck Audit v1.0.0"
        comment = "https://wildduck.email"
        [app.pgp.sign]
            key = "./config/sign.pem"
            password = "08Sgipx582LZFNxjMQVRDH5kf1l"
    [app.hash]
        algo = "sha256"

[web]
    enabled = true
    workers = 2
    port = 7002
    host = "127.0.0.1"
    proxy = false
    postSize = "5MB"

    [web.cookie]
        #   pwgen -N 1 -s 64
        name = "wdac"
        secret = "a cat"
        secure = false

[dbs]
    mongo = "mongodb://127.0.0.1:27017/wildduck"
    redis="redis://127.0.0.1:6379/7"
